Add storageClassName and volumeMode to datavolumes
ansible-collections/community.kubevirt pull request #19
Opened 2021-07-14 16:12 UTC by snecklifter

##### SUMMARY
Currently the code ignores additional parameters and both
storageClassName and volumeMode are commonly used. This commit
adds them.

Fixes #12

##### ISSUE TYPE

- Bugfix Pull Request

##### COMPONENT NAME
kubevirt_vm

##### ADDITIONAL INFORMATION
N/A

2021-07-22 10:21 UTC, Akasurde commented
@snecklifter Thanks for the contribution. The CI failure is not related to this PR.

2021-07-22 10:22 UTC, Akasurde requested changes

2021-07-22 10:22 UTC, Akasurde commented on plugins/module_utils/kubevirt.py
> +                'storageClassName': dv.get('pvc').get('storageClassName'),
Please create a [changelog fragment](https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment). See [this fragment](https://github.com/ansible/ansible/blob/c2f528b7686c9573aa8493357219e0bbe4416dd3/changelogs/fragments/reboot-change-default-boot-command.yaml) as an example.

2021-09-01 07:55 UTC, Andersson007 commented
cc @tima as a maintainer could you please take a look?

cc @machacekondra @mmazur @pkliczewski you were in the team_kubevirt in ansible/ansible before this stuff was moved to this repo. Are you interested in becoming maintainers of this repository?
We can help with figuring out how to maintain this collection if needed.

The failing check is unrelated, please ignore.

2021-09-03 08:02 UTC, Andersson007 commented
@snecklifter thanks for rebasing! I pinged folks internally as the team_kubevirt members do not respond...

2021-09-03 08:03 UTC, Andersson007 commented
@Akasurde the changelog has been added. If you know anyone who can review this and the other PR, please ping them:)

2021-09-06 08:23 UTC, Andersson007 commented
@machacekondra @mmazur @pkliczewski could you please review this PR?

2021-09-06 08:58 UTC, alinabuzachis approved these changes
@snecklifter Thank you. I left one comment with minor neats. This LGTM!

2021-09-06 08:58 UTC, alinabuzachis commented on changelogs/fragments/add-missing-datavol-params.yaml
> +  - kubevirt_vm - Adds missing storageClassName and volumeMode parameters to datavol class (https://github.com/ansible-collections/community.kubevirt/issues/12)
```suggestion
  - kubevirt_vm - Adds missing ``storageClassName`` and ``volumeMode`` parameters to datavol class (https://github.com/ansible-collections/community.kubevirt/issues/12)
```

2021-09-08 04:48 UTC, Akasurde approved these changes
LGTM

2021-09-08 04:49 UTC, merged

2021-09-08 04:58 UTC, Andersson007 commented
@snecklifter thanks for the contribution! @alinabuzachis @Akasurde thanks for reviewing!