Rename kubevirt dependency
ansible-collections/community.kubevirt pull request #25
Opened 2021-09-01 15:24 UTC by tadeboro

The community.kubernetes collection has been renamed to kubernetes.core and this commit just makes sure the collection will not get stuck with the old name.

Do note that we had to introduce an upper bound in the requirements since the kubernetes.core broke backward compatibility with version 2.0.0.

##### ISSUE TYPE

- Bugfix Pull Request

2021-09-01 18:02 UTC, Andersson007 commented
@tadeboro thank you much!

CC @Akasurde

2021-09-01 18:05 UTC, Andersson007 commented
https://github.com/ansible-collections/kubernetes.core/issues/219

2021-09-01 18:12 UTC, Andersson007 approved these changes
LGTM

2021-09-02 06:23 UTC, Andersson007 commented
```
<•andersson007_> Andrew Klychkov 
does anyone have any ideas why the doc fragment can't be found https://github.com/ansible-collections/community.kubevirt/pull/23 ? It exists:)
10:33 AM <github-linkbot> 
https://github.com/ansible-collections/community.kubevirt/pull/23 | open, created 2021-09-01T08:09:14Z by Andersson007: Change dependency from community.kubernetes to kubernetes.core  
10:36 AM 
→ Nukien2 joined (~Nukien2@ool-ad022598.dyn.optonline.net)
10:40 AM <•gwmngilfen-work> @gwmngilfen:ansible.im 
Morning
10:41 AM 
⇐ eramirez quit (~eramirez@49.149.131.61) Read error: Connection reset by peer
10:42 AM <felixfontein> Felix Fontein 
andersson007_: zuul's third party check doesn't care about collection dependencies, so if that doc fragment comes from a dependency, it will fail
10:42 AM 
→ eramirez joined (~eramirez@49.149.131.61)
10:42 AM <felixfontein> Felix Fontein 
andersson007_: that's why the third party check always fails in c.g for stable-1 (when we still had dependencies)
10:42 AM 
⇐ eramirez quit (~eramirez@49.149.131.61) Read error: Connection reset by peer
10:43 AM <felixfontein> Felix Fontein 
I would really add proper CI to that collection (at least sanity tests), and not just zuul third party, since that one is really basic (and very slow for what it does)
```

2021-09-02 06:38 UTC, Akasurde requested changes
how about we make following changes - 

- community.kubevirt 1.* depends upon community.kubernetes 1.*
- a major release like 2.0 and making it dependent on kubernetes.core 2.0

2021-09-02 07:35 UTC, tadeboro commented
From IRC:

    08:56 <tadeboro> I will wait with 25 a bit more so that people can decide if we want to keep k.c constrained or fix the community.kubevirt to work with 2.0.0.

I just wanted to make sure communty.kubevirt does work with properly restricted kubernetes.core, but as state above, if someone has time to actually fix the collection and make it work with k.c 2.x.y, even better.

2021-09-02 08:07 UTC, Andersson007 commented
@tadeboro folks will discuss which way to follow and will put something in here soon, thank you!

2022-03-22 14:23 UTC, jseguillon commented
Hi there, I read there were plans to move away from community.k8s to core.k8s. 

This sounds important to me since with community.k8s we're stuck [on this issue ](https://github.com/kubernetes-client/python/issues/1333) and forced to keep `openshift<0.11`.

Could someone give me a status on this ? Thanks.

2022-03-23 09:21 UTC, Andersson007 commented
@jseguillon hi, thanks for asking!
The collection definitely needs hands, so if you know anyone interested in becoming a maintainer, we'd be happy to discuss this.

2022-03-24 07:00 UTC, Andersson007 commented
@jseguillon moreover, as the collection is unmaintained and is broken in Ansible 5, it's going to be removed from the package (we are developing the process now https://github.com/ansible-collections/overview/pull/201).
Though it will still be available on Galaxy for manual installation.
We are looking for new maintainers who can fix and continue to update the code to keep the compatibility with k8s.core.
So if you know folks who use the collection and want to maintain it, please ask them to respond to the [issue](https://github.com/ansible-collections/community.kubevirt/issues/27).
If there are new maintainers, the collection will not be removed from the package.

2022-09-07 12:45 UTC, tadeboro commented
Closing since collection is dying.

2022-09-07 12:45 UTC, closed without merging

2022-09-07 12:48 UTC, Andersson007 commented
@tadeboro thanks!